/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 axo.glb --transform
*/

import React, { useRef,useEffect,useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/axo-transformed.glb')
  const { actions } = useAnimations(animations, group)
  const [currentAnimation, setCurrentAnimation] = useState('rumba');

  useEffect(() => {
    actions.rumba.play();

    const animationInterval = setInterval(() => {
      const animationNames = ['thanks','Dancingone', 'chicken', 'dance3', 'fight', 'rumba'];
      const currentAnimationIndex = animationNames.indexOf(currentAnimation);
      const nextAnimationIndex = (currentAnimationIndex + 1) % animationNames.length;
      const nextAnimation = animationNames[nextAnimationIndex];

      actions[currentAnimation].fadeOut(0.5); // Transition: fade out the current animation
      actions[nextAnimation].reset().fadeIn(0.5).play(); // Transition: reset and fade in the next animation

      setCurrentAnimation(nextAnimation);
    }, 9000);

    return () => clearInterval(animationInterval);
  }, [actions, currentAnimation]);




  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.mixamorigHips} />
          <primitive object={nodes.Ctrl_Master} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Left} />
          <primitive object={nodes.Ctrl_Hand_IK_Left} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Right} />
          <primitive object={nodes.Ctrl_Hand_IK_Right} />
          <primitive object={nodes.Ctrl_Foot_IK_Left} />
          <primitive object={nodes.Ctrl_LegPole_IK_Left} />
          <primitive object={nodes.Ctrl_Foot_IK_Right} />
          <primitive object={nodes.Ctrl_LegPole_IK_Right} />
        </group>
        <skinnedMesh name="Cube027" geometry={nodes.Cube027.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube027.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/axo-transformed.glb')